### ISSUE TITLE
Add option to convert GIF images to MP4

### ISSUE THREAD

**Issue by Mhowser** [caydey/ffshare#1]
GIF file sizes are huge compared to mp4, so having a way to quickly and easily convert a gif animated image to mp4 would be very handy.

https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line

There are some one-liners for ffmpeg that you might be able to use in this app.

**Comment by caydey** [comment]
Added feature [Commit](https://github.com/caydey/ffshare/commit/6f200e033992ad07648b053e2e6e8505952e77d9) will be available in Version 1.1.2

**Comment by Mhowser** [comment]
Thank you!
