### ISSUE TITLE
[Feature request] Add audio support

### ISSUE THREAD

**Issue by tbart** [caydey/ffshare#10]
Hi & thanks for this app, much appreciated!

Would adding audio support be hard?
As a musician, I like to record in full quality (wav) but a quick compression option for sending audio as a preview for example would be grand.
Choosing some sensible default like ogg or aac in mp4 (both codecs every browser should be able to play) would seem a good idea, but an option to enter a custom ffmpeg command/parameter list would also be very helpful so everyone can set their preferred options. Probably savable as profiles as well.

**Comment by gbdomubpkm** [comment]
@tbart What you say is right. In the meantime, you can try https://f-droid.org/en/packages/protect.videoeditor that i discovered very recently too. There are good ideas in this app. Not maintained but should partially work (for me yes android 11).
