### ISSUE TITLE
"Error compressing media" on x86_64 emulator

### ISSUE THREAD

**Issue by vszabo2** [caydey/ffshare#11]
The app installs successfully on an x86_64 emulator and tries to use the arm64-v8a binaries, using translation https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html. When I try to share a photo to FFShare, it fails with a toast "Error compressing media," and the log shows "E/ffmpeg-kit: SAF fd 2 not found."

This is caused by commit 40fb4bc0702a201eef9951de89232952693602da (#7; Removed support for x86 cpu architectures, Reduces build size). Running the app on the x86_64 emulator works properly if I revert this commit.

When I check out 0cdbdc5e088def49335a228d42c25e425481bccc, the app works properly on the emulator if I install with `adb install --abi x86_64 app/build/outputs/apk/debug/app-debug.apk`, but produces the error mentioned above if I install with `adb install --abi arm64-v8a app/build/outputs/apk/debug/app-debug.apk`.

This is confusing since I didn't see any warning about ABI incompatibility when I ran the arm64-v8a version. Perhaps the incompatibility with the x86_64 emulator should be mentioned in the project documentation.

**Comment by caydey** [comment]
I'll change it so only the release build wont have support for x86 and the debug build will, allowing the app to work with android studios emulator for testing
