### ISSUE TITLE
App crashes for bigger input files

### ISSUE THREAD

**Issue by ahmadjamalmughal47** [caydey/ffshare#113]
**Describe the bug**
It leaves no log behind, but when I input bigger files, like bigger than 20 mb, say, it just crashes. Then when I clear data and cache it starts working again. I noticed it accumulates large cache after each conversion, probably does not delete cache after it has already been shared.

**Comment by psour** [comment]
Pixel 9, Android 15 Graphene, Fdroid build 1.3.2 is not working.
Neither through share menu nor  selecting file directly. All permissions granted.
After removing the app and reinstalling, 1.3.2 worked again. Maybe incompatible inapp settings?

**Comment by caydey** [comment]
I think this has been solved by changes made to solve #115
