### ISSUE TITLE
Changing Video crf results in crash on conversion

### ISSUE THREAD

**Issue by zmetzing** [caydey/ffshare#115]
**Describe the bug**

On my Pixel 6a with Graphene OS, I can induce a crash by changing the value of "Video crf" after installing the application or clearing app storage. It is important to note that changing the value back to 23, the default, does not fix the problem. Only by uninstalling/reinstalling or clearing application storage does the application stop crashing and successfully compress a video.

**Settings applied**
Change "Video crf" to any value. Attempt to compress a video. Observe crash.

**App Logs**
Android log attached, as app crashes before creating its log.
[Error_in_FFShare_b840d3be90f8.txt](https://github.com/user-attachments/files/17737787/Error_in_FFShare_b840d3be90f8.txt)

**File used**

https://github.com/user-attachments/assets/b043ead7-ca53-4ca1-a30e-4b643e74429d

**Comment by Spielmops** [comment]
I can this error confirm: ffshare works with unchanged settings, but if crf is changed, ffshare crashes immediately and without logfile.

Spielmops

**Comment by caydey** [comment]
Fixed in 7895a7d378466eecdf583e839d0eaf5316281910

**Comment by zmetzing** [comment]
I can verify that the fix does resolve the issue.
