### ISSUE TITLE
Add options for Trim

### ISSUE THREAD

**Issue by rancidfrog** [caydey/ffshare#13]
Since you are using ffmpeg, there are many additional options you can use when executing commands.
Personally, trim can be very useful.

Some commands:
Audio convert to mp3,
ffmpeg -i i.m4a -c:v copy -c:a libmp3lame -q:a 4 o.mp3

replace audio in video
ffmpeg -i i.mp4 -i o.mp3 -c:v copy -map 0:v:0 -map 1:a:0 new.mp4

Video trim,
ffmpeg -ss 00 -i i.mp4  -reset_timestamps 1 -avoid_negative_ts make_zero -to 11.5   o.mp4

Some commands need to be verified to make sure timestamps are regenerated, so that the original video timings or negative time does not appear

Also, another step would be for simple video playback so that user can determine time for trim etc.

**Comment by caydey** [comment]
I don't think options like these would be suited for this app, it's only intended as a simple way to compress videos/images before sharing them and adding these options would make it more like a video editing app (which there already are plenty of) and stray from its original source.

**Comment by rancidfrog** [comment]
Currently there is no FOSS editor being maintained.
Which is why I suggested the trim feature.
Trimming does not need any reencoding so it would actually be very suited to your sharing concept, as sometimes you just one to share a specific part of the video.
