### ISSUE TITLE
[feature request] Confirmation window before conversion

### ISSUE THREAD

**Issue by gbdomubpkm** [caydey/ffshare#19]
First, thank you for your great work !!

If I'm not mistaken, the conversion starts directly. I will see a confirmation window before the conversion gathering the characteristics of the basic file and the parameters of the converted file. I would like to see the crf video of the input file appear (there is one? 🙂) if possible.

The window will offer:
  - OK ;
  - cancel ;
  - conversion settings.

Just a suggestion 🙂

**Comment by caydey** [comment]
Merging to #17
