### ISSUE TITLE
[feature] target specific filesize

### ISSUE THREAD

**Issue by AeliusSaionji** [caydey/ffshare#2]
Many web services have upload limits - for example discord has an 8MB limit. A very common task I perform is cutting down a video until it's just under the limit of whatever service I want to upload to.

Thanks!

**Comment by GhostOfJericho72** [comment]
I second this. 
For myself, this would be extremely helpful for Discord.

**Comment by ShockedCoder** [comment]
I third.

**Comment by tomkel** [comment]
Can also add 100M limit please? Thank you so much.

And is there a reason why 192k or 256k audio not supported?

**Comment by caydey** [comment]
Sure, Are there any other limits that you would like or think would be needed.
I didn't see the need to add 192k+ audio while writing the code however it makes sense that I should include it.
I'll be sure to include those changes in my next version

**Comment by tomkel** [comment]
tysm! 200M is the only other one I might need.
