### ISSUE TITLE
Release most recent versions on GitHub releases

### ISSUE THREAD

**Issue by cyberparty** [caydey/ffshare#20]
Hi,

The GitHub releases don't seem to be kept up to date with the more recent app versions. As of writing, the current release ver. is 1.2.3 (released on F-Droid on the 24th of Nov) but the most recent release on GitHub is 1.1.3 (released on the 24th of Sept). 

It would be great if this was kept up to date, so that those who prefer to download the dev-signed APKs from there can do so.

**Comment by caydey** [comment]
I'll make sure to publish releases with GitHub in the future
