### ISSUE TITLE
Support H265 HEVC

### ISSUE THREAD

**Issue by Borph** [caydey/ffshare#23]
I record videos only in H265 (OpenCamera). But the ffmpeg command seems to be hardwired to give the "-c:v h264" option. I would like to simply keep the HEVC format.

**Comment by Borph** [comment]
I converted a  video of 160mb (already HEVC) to 35mb on the PC (yeah I know) with
`ffmpeg -i in.mp4 -c:v libx265 -map_metadata 0 -movflags use_metadata_tags out.mp4`
So there seems to be some room of size reduction.

**Comment by yant0** [comment]
#5 ?

**Comment by Borph** [comment]
Related, but not the same. I'm not asking for giving custom CLI parameters, but for changing to h256 internally, or give an UI option.

**Comment by CendaCZ** [comment]
Mentioned & possible Workarounds #57
