### ISSUE TITLE
Shave 19MiB off APK size by removing audio (mp3/wav/aac) conversion support?

### ISSUE THREAD

**Issue by caydey** [caydey/ffshare#24]
I have been doing some testing and have realized that I can reduce the APK build size from 57.0MiB to 38.0MiB by removing audio (mp3/wav/aac) conversion support.

However I'm not sure if I should remove such a feature from the app only for a 33% size reduction without first getting the app users opinion.

**Comment by Borph** [comment]
Do you mean audio files like mp3, not audio inside video files? Really personal opinion here: As I never used such conversion, I could live without it and I feel 57.0MiB is a lot for an app. But it's 33% and storage is cheap... so no deal breaker in any way.

**Comment by caydey** [comment]
yes, removing mp3 file conversion, video audio is kept

**Comment by G2G2G2G** [comment]
all audio should be converted to aac or opus, not mp3. aac has massive adoption and is far more efficient than mp3. Opus has less adoption but is even more efficient..
I'd go with aac since it is a good middle ground

But you can remove mp3/wav for 100% sure, no reason to have them

**Comment by Amateurintheflesh** [comment]
I think removing audio support is totally fine. just doing `c:a copy` in most cases is enough, as reencoding audio when the audio streams are relatively small anyway is fine

**Comment by 825i** [comment]
> all audio should be converted to aac or opus, not mp3. aac has massive adoption and is far more efficient than mp3. Opus has less adoption but is even more efficient.. I'd go with aac since it is a good middle ground
> 
> But you can remove mp3/wav for 100% sure, no reason to have them
> 
> original audio on phones is usually low bitrate too so prob doesn't matter if you had no audio conversion at all, I'd be using aac though if it was available. 64kbps is pretty much all that is needed for non-music

What this guy said. It's not needed. aac audio is preferred, or leave audio basically untouched. Basically no smartphones are recording audio above 196k anyway.

**Comment by caydey** [comment]
marking as closed since I now build split APK's to GitHub's releases page
