### ISSUE TITLE
Default folder to save videos

### ISSUE THREAD

**Issue by EdieN** [caydey/ffshare#33]
It would be nice to have an option to save all compressed media in a folder selected by the user.

It's frustrating when the compression process take some time and when it's completed the pop-up to share show up, but you accidentally touch the screen making the pop-up close and losing your compressed media.

**Comment by montvid** [comment]
Yes, so many problems if the transcoded video is not saved. Also there are problems with android 13 or something so simetimes it is not possible to save the file... Please implement a save to folder function, thanks!
