### ISSUE TITLE
Compression fails if the screen timeout

### ISSUE THREAD

**Issue by 825i** [caydey/ffshare#35]
If the screen goes black whilst compressing due to screen timeout, the compression fails.

**Comment by zetaomegagon** [comment]
Assuming this is related to (issue #4)[https://github.com/caydey/ffshare/issues/4#issuecomment-1295744006]

**Comment by gbdomubpkm** [comment]
@825i To avoid that run [coffee ](https://f-droid.org/en/packages/com.github.muellerma.coffee/) when ffshare is running

**Comment by caydey** [comment]
Merging to #4
