### ISSUE TITLE
Split APKs

### ISSUE THREAD

**Issue by DoozyDoz** [caydey/ffshare#36]
- Can we separate the ffmpeg binaries from the shipped apk and have them downloadable at demand, this has several advantages. once the apk is small :
- The app will easily get installed by several users.
- The users will only get the file they need  and  tailored to their phone architecture

For example
- Some users only use this for video compression never audio, so when the user installs the app the ffmpeg binaries are not present then  the first time they try to share a video they are asked to download the necessary files, these files will be small since its specific to their architecture, weigh smaller than our 58 megabyte apk.
- To do this we just have to split the binaries for different architectures and host them here in GitHub or any other fast server. We pick the phone system details and use them ro decide which binaries they need to download.

**Comment by caydey** [comment]
Modified Gradle to build 6 separate APK's, (`arm64`, `armeabi`, `arm64+armeabi`) * (`full`, `video`)
with `full` allowing all features and `video` not supporting the audio file (mp3 / ogg) compression feature
I'll have these APK's in the GitHub releases
