### ISSUE TITLE
Settings Option: ignore output if larger than input file

### ISSUE THREAD

**Issue by DoozyDoz** [caydey/ffshare#37]
- Sometimes the compressed video is weigh bigger than the input video

**Comment by caydey** [comment]
This sometimes happens when the original video is already efficiently compressed.

**Comment by caydey** [comment]
Closing as there is a toast message that informs the user if the resulting file is larger and it is easy for them to cancel and share the file directly, furthermore a user may want to convert an image between 2 formats which often results in a large file.
