### ISSUE TITLE
separate 'Max resolution' for JPEG and video

### ISSUE THREAD

**Issue by thymaro** [caydey/ffshare#47]
In the settings panel, there is one setting for 'max resolution' that affects both video and JPEG output. Is it possible to separate that? Most of the time, I'd like to convert video to 1080p, but pictures at 1080p are usually too small. 

FFshare is great for fast conversion to (a self chosen) standard format, but if we have to go change that standard each time before sharing, it's no standard anymore.

FFShare 1.2.6

**Comment by caydey** [comment]
Added separate max resolution for video & images, for the second paragraph I'm not sure what you mean but this issue will be closed as completed.

**Comment by thymaro** [comment]
We don't talk about the second paragraph. The suggested addition is likely to accomplish the desired result. Prosce!
