### ISSUE TITLE
Add ffmpeg options to be manually changed

### ISSUE THREAD

**Issue by tiziodcaio** [caydey/ffshare#5]
For example, adding h265 support

**Comment by G2G2G2G** [comment]
agreed, I want to use h264, or any codec from this century would be fine with me. But it is hard coded for mpeg4

**Comment by G2G2G2G** [comment]
@caydey  what do we do, is there no codec set at all? Doesn't look like there is

![image](https://user-images.githubusercontent.com/50514477/197375940-afe4b8ac-4776-4dbc-8589-916c0c20bc44.png)
we just set this here? IDK how to build, I've never built an app, especially not kotlin. 

I looked through all the params and I see no mention of codecs or anything of the sort. I guess making it an option would be better but h264 is supported by everything

**Comment by caydey** [comment]
The libx264 is not available because I'm using the 'full' version of ffmpeg-kit not 'full-gpl', I'm working on changing it now and will make h264 the default video encoder in the next release.

**Comment by caydey** [comment]
I've done some testing with the h265 (hevc) codec and it is painfully slow on mobile devices with little to no size reduction so I will not be including it at the moment. I've made h264 the default codec for videos.
I don't want to make the ffmpeg command manually changeable as different different commands are ran based on different options and input files.
