### ISSUE TITLE
Manualy select media files within the app. PROBLEM ?

### ISSUE THREAD

**Issue by gbdomubpkm** [caydey/ffshare#53]
V 1.2.7 github

Hello !

I wanted to try this feature and I was scared!

I pressed the file selection location then got a warning message about my SD card asking me what I want to do with it as if it was empty...

With my file manager, I couldn't find any files on the card!! I cleared the app data, uninstalled ffshare, turned off and on the smartphone and everything is ok again. 😰

Android 12 AOSP.

Please check that everything is ok with this feature. THANKS !

**Comment by caydey** [comment]
I can guarantee you that nothing in my app would of caused this,
what is most likely is that opening up the file selector would've made your phone scan for your SD card only to detect that there is an error with it.
This issue will be closed.

**Comment by gbdomubpkm** [comment]
I reinstalled ffshare github v 1.2.7, gave permission to access media files and retested. I confirm that there is indeed a problem that is triggered with ffshare without knowing the cause, since I have no problem with my other apps which have direct access to the SD card.

**Comment by gbdomubpkm** [comment]
Hello again.

So this time I downloaded the **F-droid apk** and it **works without any problem!**

Android asks if I want to allow FFShare to access media content. With the Github package I don't have that. And apparently giving the access permission by myself doesn't solve the problem with the github apk.

**Comment by gbdomubpkm** [comment]
Reopen ?
