### ISSUE TITLE
Invalid file (heic)

### ISSUE THREAD

**Issue by Validbit** [caydey/ffshare#57]
When I'm trying to use the share dialog I couldn't sometimes convert files from most gallery apps (sometimes even native and Google Photos) with 'invalid file' toast - from different apps on some days.

I'm uncertain what exactly is causing the issue but the logs won't show it even with 'Enable logs'. 

In most cases however (all galleries and app itself) it happens with heic (heif) images. If that's the case is HEIF/HEIC support planned in the near future?

It's been happening for weeks across multiple devices now thus I'm asking here and am available to provide more info if needed. I use Realme GT2 (Android 13).

**Comment by caydey** [comment]
Unfortunately no version of ffmpeg supports HEIF conversion https://trac.ffmpeg.org/ticket/6521 and therefore it is not possible to implement this feature.

**Comment by Validbit** [comment]
I see, but the thread is quite old (though relevant) and latest helpful info was posted 11 months ago. (it's commonly requested, since it's native option in most new smartphones (and seems like default in iPhones)

From what I've found, [this](https://github.com/Nuevo009/makeheic-avif) (or libhevc) **could work well** as a workaround (still using ffmpeg), if you'd want to try. If I had more experience I'd help.
