### ISSUE TITLE
Allow any custom command line arguments for `ffmpeg`

### ISSUE THREAD

**Issue by baack** [caydey/ffshare#69]
Allow setting any custom command arguments for `ffmpeg`. If is it possible in the project.

It will be a huge step forward for advanced users, who will be able to do almost anything they want, e.g. make time-lapses and other stuff that is not going to be available via app's GUI any time soon.

**Comment by scorgn** [comment]
I would also love to be able to do this. To be able to have it preset to convert to .gif for example when shared to ffshare, or even better would be to allow multiple ffmpeg command presets you can choose from when sharing to ffshare.

**Comment by caydey** [comment]
Closed by #80
