### ISSUE TITLE
Décompression apk too large

### ISSUE THREAD

**Issue by Erictheplague** [caydey/ffshare#7]
Why's a décompression apk large?? It should be minimal and bloat free

**Comment by G2G2G2G** [comment]
possibly because ffmpeg itself is large?

**Comment by caydey** [comment]
not only is ffmpeg very large but the apk compiles it for 4 of the android architectures (arm64-v8a, armeabi-v7a, x86, x85_64)

**Comment by gbdomubpkm** [comment]
The topic of discussion is the size of the apk ?

The Video Transcoder apk also based on ffmpeg is only 37.8 mb. ffshare more than 100mb.
Their purpose is not totally identical, it is true, but any non-specialist (like me 🙂) may wonder why such a difference in size.

**Comment by caydey** [comment]
I've managed to get the apk build size down to <60mb by removing x86 architecture support.
It is possible for me to further reduce the size of the app to <32mb by only compiling for the armeabi-v7a as arm64 processors are able to read it, however this is at large performance cost and the app is noticeably slower.

**Comment by vszabo2** [comment]
Another option is to create different APKs for different architectures, as described here: https://developer.android.com/studio/build/configure-apk-splits
It's possible to publish multiple APKs to F-Droid, but it's not well-supported at the moment: https://gitlab.com/fdroid/fdroidserver/-/issues/995
