### ISSUE TITLE
when phone goes to sleep conversion stops

### ISSUE THREAD

**Issue by angryseptagon** [caydey/ffshare#70]
When my screen goes off or I switch away from the app, the conversion stalls. My device isa galaxy S20+.
![Screenshot_20240211_185900_FFShare](https://github.com/caydey/ffshare/assets/44549503/af947f58-74b0-4fd4-bb09-cc02d862c002)

**Comment by Catfriend1** [comment]
Same on Xiaomi 13 HyperOs 1.0

**Comment by ccrowles** [comment]
Same here, ZenFone 9, android 14.

**Comment by tausiftaha21** [comment]
Same here, Samsunf A52s 5G

**Comment by JetpackJackson** [comment]
Same here, Samsung S21 5G

**Comment by Gamer750** [comment]
Same here

**Comment by esetleges** [comment]
Conversation stops if the app is not in front or screen goes off

**Comment by Nalajalan** [comment]
+1 It makes the app quite unusable...

**Comment by caydey** [comment]
A simple solution would be to prevent the phone from sleeping while a conversion is in progress
