### ISSUE TITLE
when app is in background conversion stops

### ISSUE THREAD

**Issue by Nalajalan** [caydey/ffshare#84]
Hi,

Sorry to kind of "reopen" this thread : https://github.com/caydey/ffshare/issues/70

But for me it is still a bug.  

Prevent the phone from sleeping while a conversion is in progress is a good workaround but to keep screen on during long conversion is not super and the problem happens when app is in the background too, so you can't use the phone during conversion.

It is quite ok for very little video but for me make the app almost not usable for "bigger" videos (more than 1 or 2 minutes).

Thank a lot for your app that does a very useful job (the only one in foss) but this problem is almost killing all his purpose for me.

**Comment by caydey** [comment]
There is already a ticket open for the issue described #4, closing
