### ISSUE TITLE
AC3 audio codec transformed into vorbis after conversion

### ISSUE THREAD

**Issue by gbdomubpkm** [caydey/ffshare#91]
Hello.
By retaining the AC3 audio input codec, this is transformed into a vorbis output.  Is this normal?

**Comment by gbdomubpkm** [comment]
Conversely, I also think that ffshare cannot convert the vorbis format into another audio format (for example aac) when the audio input format is vorbis.

**Comment by caydey** [comment]
Merging to #92;
